---
cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.1,172.29.236.50"
  - "172.29.240.1,172.29.240.50"
  - "172.29.244.1,172.29.244.50"

global_overrides:
  internal_lb_vip_address: 172.29.236.5
  external_lb_vip_address: openstack.XXX.XXX # FQDN to access from external network
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "enp1s0f0"
        container_type: "veth"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  osa10:
    ip: 172.29.236.10

# load balancer
# Ideally the load balancer should not use the Infrastructure hosts.
# Dedicated hardware is best for improved performance and security.
haproxy_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# rsyslog server
log_hosts:
  osa10:
    ip: 172.29.236.10

###
### OpenStack
###

# keystone
identity_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# cinder api services
storage-infra_hosts:
  osa1:
    ip: 172.29.236.1

image_hosts:
  osa2:
    ip: 172.29.236.2

# placement
placement-infra_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# nova api, conductor, etc services
compute-infra_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# horizon
dashboard_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# neutron server, agents (L3, etc)
network_hosts:
  osa1:
    ip: 172.29.236.1
  osa2:
    ip: 172.29.236.2
  osa3:
    ip: 172.29.236.3

# nova hypervisors
compute_hosts:
  osa10:
    ip: 172.29.236.10

storage_hosts:
  osa1:
    ip: 172.29.236.1

    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.29.244.1"
          
